<?php
    $real_orders = Mage::getResourceModel('sales/order_collection')
            ->addAttributeToSelect('*','shipping_firstname')
            ->joinAttribute(
                'shipping_firstname',
                'order_address/firstname',
                'shipping_address_id',
                null,
                'left'
            )
            ->joinAttribute(
                'shipping_middlename',
                'order_address/middlename',
                'shipping_address_id',
                null,
                'left'
            )
            ->joinAttribute(
                'shipping_lastname',
                'order_address/lastname',
                'shipping_address_id',
                null,
                'left'
            )
            ->addAttributeToFilter('state',array('in' => array('new','processing','complete')))
            ->addAttributeToSort('created_at', 'desc')
            ->setPage(1,10);

    $orders_array = array();
    if( sizeof($real_orders->getItems()) > 0 ){
        foreach ($real_orders as $order){
            $order_real_id = $order->getRealOrderId();
            $country_id = $order->getShippingAddress()->getData('country_id');
            $firstname  = $order->getShippingAddress()->getData('firstname');
                
            foreach ($order->getParentItemsRandomCollection(20) as $_item){
                $product_id = $_item->getProduct()->getId();
                $product2 =  Mage::getModel('catalog/product')->load($product_id);

                $orders_array[$order_real_id .'_'.$product_id] = array(
                    'akey'        =>  $order_real_id .'_'.$product_id.'_real',
                    'country_id'  =>  $country_id,
                    'firstname'   =>  $firstname,
                    'url'         =>  $product2->getProductUrl(),
                    'image'       =>  Mage::helper('catalog/image')->init($product2, 'small_image')->resize(90,120)->__toString(),
                    'name'        =>  $product2->getName(),
                    'price'       =>  Mage::helper('core')->formatPrice($product2->getPrice()),
                    'finalprice'  =>  Mage::helper('core')->formatPrice($product2->getFinalPrice()),
                    );
            }
        }
    }


    $pending_orders = Mage::getModel('webhome/webhome')
            ->getCollection()
            ->addFieldToFilter('customer_email',array('in' => array('457662258@qq.com','support@d-daydress.com')))
            ->addFieldToFilter('is_active',1)
            ->addFieldToFilter('reserved_order_id',array(
                                                        array('notnull' => true),
                                                        )
                                                );
    if( sizeof($pending_orders) > 0 ){
        foreach($pending_orders as $order){
            $order_real_id = $order->getReservedOrderId();
            $order_id = $order->getEntityId();
            $address = Mage::getModel('sales/quote_address')->getCollection()
                        ->addFieldToFilter('address_type','shipping')
                        ->addFieldToFilter('quote_id',$order_id);
            $country_id = '';
            $firstname  = '';
            foreach($address as $ads){
                $country_id = $ads->getCountryId();
                $firstname  = $ads->getFirstname();
                break;
            }
            $items =  Mage::getModel('sales/quote_item')->getCollection()
                ->addFieldToFilter('quote_id',$order_id);
            foreach($items as $item){
                $product_id = $_item->getProductId();
                $product2 =  Mage::getModel('catalog/product')->load($product_id);
                $orders_array[$order_real_id.'_'.$product_id] = array(
                    'akey'        =>  $order_real_id.'_'.$product_id.'_pending',
                    'country_id'  =>  $country_id,
                    'firstname'   =>  $firstname,
                    'url'         =>  $product2->getProductUrl(),
                    'image'       =>  Mage::helper('catalog/image')->init($product2, 'small_image')->resize(90,120)->__toString(),
                    'name'        =>  $product2->getName(),
                    'price'       =>  Mage::helper('core')->formatPrice($product2->getPrice()),
                    'finalprice'  =>  Mage::helper('core')->formatPrice($product2->getFinalPrice()),
                    );
            }
        }
    }
    rsort($orders_array);
    Mage::log($orders_array);
?>


<?php if( count($orders_array) ):?>
    <div class="home_product_title"><h3>Recent Orders</h3></div>
    <div class="recent_orders">
        <?php foreach ($orders_array as $order_item):?>
                <a class="recent_order item" href="<?php echo $order_item['url'];?>">
                    <img src="<?php echo $order_item['image'] ;?>">
                    <span class="proinfo">
                        <span class="name"><?php echo $order_item['name'];?></span>
                        <span class="check-it">Check it</span>
                        <span class="old-price"><?php echo $order_item['price'];?></span>
                        <?php if($order_item['price'] != $order_item['finalprice']):?>
                            <span class="special-price"><?php echo $order_item['finalprice'];?></span>
                        <?php endif;?>
                        <?php if($order_item['country_id']): ?>
                            <span class="shippingto">ship to <?php echo $order_item['country_id'].
                                        '<i class="flag flag-'.strtolower($order_item['country_id']).'"></i> '.
                                        ucfirst($order_item['firstname']) ?></span>
                        <?php endif;?>
                    </span>
                </a>
        <?php endforeach;?>
    </div>
    <script>
        jQuery(document).ready(function(){
            jQuery('.recent_orders').each(function() {
                if(jQuery('.item', this).length > 0) {
                    jQuery(this).owlCarousel({
                        loop: true,
                        items: 4,
                        nav: false,
                        dots: false,
                        margin:10,
                        autoplay: true,
                        autoplayTimeout:8000
                    });
                }
            });
        });
    </script>
<?php endif;?>