<?php $top_countdowns = Mage::getModel('ibanners/group')->loadByCode('website_top_countdown')->getBannerCollection();?>

<?php if(count($top_countdowns)): $i=0;?>
    <?php foreach($top_countdowns as $top_countdown): $i++;?>
        <div class="top_countdown" style="background-image: url(<?php echo $top_countdown->getImageUrl();?>);">
            <div class="adv">
                <p class="advBanner">
                    <a title="<?php echo $top_countdown->getTitle()?>" href="<?php echo $top_countdown->getUrl();?>"></a>
                    <a class="CloseBtn"><img src="/skin/frontend/pc/default/images/commont/closed.png"></a>
                </p>
                <p class="time-list">
                    <span id="topcountdown<?php echo $i;?>" class="PositionAbsolute"></span>
                    <script type="text/javascript">
                        jQuery(document).ready(function(){
                            <?php $date_time = strtotime($top_countdown->getAltText()); ?>
                            setInterval(function(){countdown('topcountdown<?php echo $i?>',
                                <?php echo date("Y",$date_time)?>,
                                <?php echo date("m",$date_time)?>,
                                <?php echo date("d",$date_time)?>,
                                <?php echo date("H",$date_time)?>,
                                <?php echo date("i",$date_time)?>,
                                <?php echo date("s",$date_time)?>)},1000);
                        });
                    </script>
                </p>
            </div>
        </div>

    <?php endforeach;?>

    <script>
        jQuery(document).ready(function(){
            jQuery(".CloseBtn").click(function(){
                jQuery(".top_countdown").slideUp();
            });
        });
    </script>

<?php endif;?>
