<div class="help_right">
    <style type="text/css">
        .DetailText p.DetailTitle {
            margin-top: 10px;
        }
        .DetailText p.DetailTitle span.Title {
            background: url(/skin/frontend/pc/default/images/page/title-bg.jpg) no-repeat;
            color: #fff;
            font-weight: bold;
            width: 76px;
            height: 17px;
            text-align: center;
            line-height: 17px;
            padding-right: 5px;
        }
        .DetailList {
            background: #efefea;
            width: 500px;
            margin-top: 10px;
            *zoom:1;
        }
        .DetailList:after{
             display:block; content:"clear"; height:0; clear:both; overflow:hidden; visibility:hidden;
         }
        .DetailList p.left {
            width: 17px;
        }
        .DetailList ul.List {
            padding: 10px 25px;list-style: disc outside none;
        }
        .DetailList ul li {
            line-height: 26px;
            list-style: none;
        }
        .DetailList ul.Lists {
            padding: 10px 0 10px 40px;
            border-left: #d7d7d2 dashed 1px;
        }
        .DetailText ul.Detail_tit li {
            background: url(/skin/frontend/pc/default/images/page/list-icon.jpg) left 6px no-repeat;
            padding-left: 15px;
            list-style: none;
        }
    </style>
    <p><span style="font-size: medium;"><strong>Share To Win</strong></span></p>

    <p style="color: #644B06;font-weight: bolder;margin-bottom: 8px;padding: 0 0 6px 3px;display: block;border-bottom:1px solid #DDDDCD;font-size: 14px;">
        Sharing Your Purchase Experience & Win Coupon Rewards
    </p>

    <p>
        <img style="float:right;margin: 30px 150px;" src="/skin/frontend/pc/default/images/page/free-img.jpg"/>
        <span>
            <br/>
            Exciting news! In order to express our thanks for all the support we’ve been receiving from customers, D-daydress will be dedicating to present our latest giveaway –Free To Get a $5-$15 coupon by sharing your shopping experience, only for D-daydress customers!
            <br/><br/>
            We’re kicking things off today by giving away a $15, $10, $5 coupon to every customer who shares or leaves a comment about her shopping experience. Basically, this is the perfect and direct way for saving. So how do you get it?
        </span>
    </p>


    <div class="DetailText">
        <h3 style="margin-top:30px;font-size: x-large;">How to Enter</h3>
        <p>Entering to get the coupon is super simple and only takes a minute!</p>
        <p class="DetailTitle cls"> <span class="Title left">Step one</span>Share your shopping experience.</p>
        <p>You have two way: 1. Share it at our website     2.Share it at any other website, forums or blog.</p>
        <p>Make your entry as general or specific as you want – you can post the pictures of your look in our dress, or list specific pieces you bought or just show general ideas of your purchasing! <strong style="color:#f39;">It is appreciated if your reviews could contain the link of our products if you post at other website.</strong> These are some websites and forums for you to refer:</p>
        <div class="DetailList cls">
            <p class="left" style="margin:0;width:17px;height:176px;background:url(/skin/frontend/pc/default/images/page/list-img.jpg)"></p>
            <ul class="List left">
                <li>http://www.trustpilot.com</li>
                <li>http://www.resellerratings.com/</li>
                <li>http://www.bizrate.com/</li>
                <li>http://www.weddingbee.com/</li>
                <li>http://www.sitejabber.com/</li>
                <li>http://www.pricegrabber.com/</li>
            </ul>
            <ul class="Lists left">
                <li>http://www.viewpoints.com/</li>
                <li>http://www.shopperapproved.com</li>
                <li>http://www.poulpeo.com</li>
                <li>http://www.reddit.com/</li>
                <li>http://www.facebook.com/</li>
                <li>http://www.instagram.com/</li>
            </ul>
        </div>
        <p class="DetailTitle cls"> <span class="Title left">Step two</span>Send the link of reviews to <a style="color:#f39; text-decoration:underline;" href="mailto:<?php echo Mage::getStoreConfig('smtppro/general/smtp_username');?>"><?php echo Mage::getStoreConfig('smtppro/general/smtp_username');?></a></p>
        <p class="DetailTitle cls"> <span class="Title left">Step three</span>The eligible entries will be notified via email after verification.</p>
        <p>And as rewards, a US$15 coupon will be given to the customers who sent awesome reviews with photo shared. A US$10 coupon will be given to those who write remarkable reviews or sharing excellent photos. However the great review texts sender will receive US$5 coupons.The selected reviews will be published on D-daydress customers gallery．</p>


        <h3 style="margin-top:30px;font-size: x-large;">Official Rules</h3>
        <ul class="Detail_tit">
            <li>This giveaway is open to customers who shop with dressilyme.com ONLY! <strong style="color:#f39;">Only entries from who have their order finished and received the goods will be eligible to win the coupon</strong></li>
            <li>Entries in positive or negative reviews will be accepted, but those inquiries for products or seeking advice will be excluded from this giveaway.</li>
            <li><strong style="color:#f39;">This giveaway is supposed to be our long-term policy.</strong> </li>
        </ul>

        <h3 style="margin-top:30px;font-size: x-large;">Share Now</h3>
        <p>If you haven’t entered the giveaway yet, what are you waiting for? Share your reviews and you will be on your way to get $15,$10,$5. We’d love to hear your story and share it with other D-daydress customers.</p>


</p>

</div>